// inventory.yml rank 55, mitigation_layer not_native
package com.detectorlab.probes.ui

import com.detectorlab.core.AndroidLayer
import com.detectorlab.core.Evidence
import com.detectorlab.core.Probe
import com.detectorlab.core.ProbeCategory
import com.detectorlab.core.ProbeContext
import com.detectorlab.core.ProbeResult
import com.detectorlab.core.ProbeSeverity

/**
 * Probe #55 — ui.canvas_fingerprint.
 *
 * **Mitigation layer: `not_native`.** The "real" canvas-fingerprint signal
 * (per A17 §6 deprioritize and the inventory `rasp_analog: none` note) is a
 * browser-side technique — JavaScript draws a glyph to a `<canvas>` 2-D
 * context and reads back the pixel data, hashing it to a per-WebView-impl
 * fingerprint. That technique is FUNDAMENTALLY UN-SNAPSHOTTABLE because it
 * requires a live WebView render, and there is no native Android RASP
 * analog — no Java/Kotlin API exposes WebView rendering deterministically
 * without instantiating a real WebView and capturing its bitmap.
 *
 * **Declarative inference here.** Since the real signal is L0 / un-snapshottable,
 * this probe stands in DECLARATIVELY for what the canvas fingerprint would
 * detect: a **non-standard WebView implementation**. The Chromium WebView
 * provider (`com.google.android.webview`) ships on essentially every retail
 * Android device shipped since 2016 (system WebView became a separately-
 * updatable component in Android 5.0 Lollipop and the Google-shipped
 * Chromium WebView is the universal default). The two declarative signals
 * the probe checks at score 0.85 each:
 *
 *   • **Chromium WebView provider MISSING (0.85)** — `com.google.android.webview`
 *     not in the PackageManager listing. Real retail Android phones never
 *     lack this package: it ships preinstalled on every Google-certified
 *     device, and it's never user-removable. Its absence implies the
 *     device is either (a) a containerized minimal Android (ReDroid, AVD
 *     stripped image) where the system_apks/ overlay didn't include
 *     Chromium WebView, or (b) a heavily de-Googled custom ROM where the
 *     user replaced the provider with an alternative. A WebView render on
 *     such a device produces a non-standard canvas fingerprint distinct
 *     from any retail device fingerprint.
 *
 *   • **Non-standard WebView provider INSTALLED (0.85)** — any of the
 *     [NON_STANDARD_WEBVIEW_PROVIDERS] (Brave/Kiwi/Bromite/DuckDuckGo
 *     WebView packages) installed. These are browse-replacement / privacy
 *     WebViews that explicitly modify Chromium's canvas rendering pipeline
 *     to randomize fingerprint outputs OR to use a non-Chromium engine
 *     entirely. A canvas fingerprint generated by any of these renders
 *     against a known-Chromium oracle distinctly. NOTE: legitimate
 *     privacy-conscious users may install these voluntarily — the FP class
 *     is documented per rank-51 honest-framing pattern. The 0.85 score
 *     remains because cloud-phone provisioning typically does NOT install
 *     privacy WebViews (cloud-phone tenants want stock-Android behavior),
 *     so the signal is high-leverage for the target evaluation surface
 *     even when the rule has a known FP class.
 *
 * **Property-surface signals (0.70 + 0.50).** The probe also reads two
 * system-property surfaces that imply a WebView misconfiguration:
 *
 *   • **WebView provider disabled at boot (0.70)** —
 *     `ro.com.google.android.webview.disabled == "1"`. This is the canonical
 *     OEM/system-build directive that disables the Chromium WebView provider
 *     from the system_apks/ side; real retail devices never set this.
 *     Combined with the package-absence signal this catches the case where
 *     the package is technically present but inert (un-snapshottable in
 *     terms of canvas rendering even if PackageManager lists it).
 *
 *   • **Safe-browsing disabled via custom WebView config (0.50)** —
 *     `persist.webview.disable_safe_browsing == "1"`. Custom builds and
 *     debug/test images sometimes flip this to bypass Google's Safe
 *     Browsing list checks on WebView page loads. Not directly a
 *     canvas-fingerprint signal but is a strong "this is a non-stock
 *     WebView config" tell — weak (0.50) because some enterprise MDM
 *     profiles set it legitimately. Calibration matches rank-51 weak-signal
 *     pattern.
 *
 * Scoring (max wins; first-match cascade in source order — strongest
 * first per the established partition pattern):
 *   0.85  PATTERN_WEBVIEW_PROVIDER_MISSING — `com.google.android.webview`
 *         absent from PackageManager listing
 *   0.85  PATTERN_NON_STANDARD_WEBVIEW_INSTALLED — any of Brave/Kiwi/
 *         Bromite/DuckDuckGo WebView packages installed
 *   0.70  PATTERN_WEBVIEW_DISABLED_PROP —
 *         `ro.com.google.android.webview.disabled == "1"`
 *   0.50  PATTERN_SAFE_BROWSING_DISABLED_PROP —
 *         `persist.webview.disable_safe_browsing == "1"`
 *   0.00  PATTERN_CLEAN — Chromium WebView provider present, no
 *         non-standard providers, no suspicious property settings
 *
 * **Confidence: 0.70 declarative.** Lower than other ui.* probes
 * (CONFIDENCE_FULL = 0.95) because the rule chain is a declarative
 * SUBSTITUTE for the real canvas-render signal, not a direct measurement
 * of it. A declarative pattern can never reach 0.95 confidence — that
 * level is reserved for direct API observations of the load-bearing signal.
 * The 0.70 floor mirrors the rank-6 KeystoreAttestationProbe declarative-
 * inference confidence floor (which also stands in for an L0 surface).
 * The 0.50 degraded confidence applies when the PackageManager view
 * returns an empty list (Android 11+ visibility filter likely in effect,
 * blocking the probe's signal source structurally).
 *
 * Reference: shared/probes/inventory.yml rank 55 (mitigation_layer not_native,
 * `rasp_analog: none` — A17 §6 deprioritize: browser-only technique with
 * no native Android RASP analog).
 */
class CanvasFingerprintProbe : Probe {
    override val id = "ui.canvas_fingerprint"
    override val rank = 55
    override val category = ProbeCategory.UI
    override val severity = ProbeSeverity.TRACE
    override val androidLayer = AndroidLayer.APPLICATION
    override val budgetMs = 100L

    companion object {
        /**
         * Canonical Chromium WebView provider package. This is the load-
         * bearing "real Android" tell: every Google-certified Android phone
         * shipped since 2016 has this package preinstalled and not user-
         * removable. Its absence implies containerized minimal Android OR
         * heavily de-Googled custom ROM — either case produces a non-
         * standard canvas fingerprint distinct from retail.
         *
         * **Note on alternate stock variants**: some devices/ROMs use
         * `com.android.webview` as the provider package instead of the
         * Google-Mobile-Services-namespaced `com.google.android.webview`
         * (notably AOSP-only builds and Huawei post-2019). The 0.85 score
         * is calibrated knowing this — the rank-51 honest-framing pattern
         * applies (some legitimate AOSP devices may trip the rule), and
         * the score is the consumer-side gating point: combine with other
         * probes before high-confidence rejection.
         */
        const val PKG_CHROMIUM_WEBVIEW = "com.google.android.webview"

        /**
         * Browse-replacement / privacy WebView packages that explicitly
         * modify Chromium's canvas rendering pipeline OR use a non-
         * Chromium engine. Each entry is a published package name from
         * the project's Play Store / F-Droid listing or canonical GitHub
         * release artifact:
         *
         *   • `com.brave.browser.webview` — Brave's standalone WebView
         *     installer (browser proper is `com.brave.browser`). Modifies
         *     canvas readback to inject per-session noise (canvas-
         *     fingerprinting protection has been a Brave feature since
         *     2018; the protection is configurable per-site).
         *   • `com.kiwibrowser.browser.webview` — Kiwi Browser WebView.
         *     Chromium-based but adds extension-API support that requires
         *     a modified rendering pipeline; canvas reads through the
         *     modified pipeline produce a distinct fingerprint.
         *   • `org.bromite.webview` — Bromite WebView (deprecated 2023 but
         *     still in deployment on long-tail devices). De-Googled
         *     Chromium fork with explicit anti-fingerprinting patches in
         *     the canvas rendering path.
         *   • `com.duckduckgo.mobile.android.webview` — DuckDuckGo
         *     WebView. Modifies canvas readback to return constant-zero
         *     hashes (the strongest anti-fingerprinting mode in the
         *     browser-WebView class).
         *
         * **FP class**: legitimate privacy-conscious users install these
         * voluntarily. Cloud-phone provisioning typically does NOT — the
         * 0.85 score is calibrated for the target evaluation surface.
         */
        val NON_STANDARD_WEBVIEW_PROVIDERS: List<String> = listOf(
            "com.brave.browser.webview",
            "com.kiwibrowser.browser.webview",
            "org.bromite.webview",
            "com.duckduckgo.mobile.android.webview",
        )

        /**
         * OEM/system-build property that disables the Chromium WebView
         * provider from boot. Real retail devices never set this; debug
         * images and some carrier-locked SKUs occasionally do during
         * factory-stage QA. A "1" value here implies the device cannot
         * render a Chromium-canonical canvas fingerprint regardless of
         * what `PackageManager` reports.
         */
        const val PROP_WEBVIEW_DISABLED = "ro.com.google.android.webview.disabled"

        /**
         * `persist.*` property that disables Safe Browsing checks in
         * WebView. Custom builds / debug images / some MDM enterprise
         * profiles flip this; a "1" value is a "this is a non-stock
         * WebView config" tell. Calibrated weak (0.50) because some
         * MDM-managed devices legitimately set it.
         */
        const val PROP_DISABLE_SAFE_BROWSING = "persist.webview.disable_safe_browsing"

        const val PATTERN_WEBVIEW_PROVIDER_MISSING = "webview_provider_missing"
        const val PATTERN_NON_STANDARD_WEBVIEW_INSTALLED = "non_standard_webview_installed"
        const val PATTERN_WEBVIEW_DISABLED_PROP = "webview_disabled_prop"
        const val PATTERN_SAFE_BROWSING_DISABLED_PROP = "safe_browsing_disabled_prop"
        const val PATTERN_CLEAN = "clean"

        const val SCORE_WEBVIEW_PROVIDER_MISSING = 0.85
        const val SCORE_NON_STANDARD_WEBVIEW_INSTALLED = 0.85
        const val SCORE_WEBVIEW_DISABLED_PROP = 0.70
        const val SCORE_SAFE_BROWSING_DISABLED_PROP = 0.50
        const val SCORE_CLEAN = 0.0

        /**
         * Declarative-inference confidence floor (0.70). Below the 0.95
         * `CONFIDENCE_FULL` other ui.* probes use because this rule chain
         * is a SUBSTITUTE for the real (un-snapshottable) canvas-render
         * signal, not a direct measurement of it. Mirrors rank-6
         * KeystoreAttestationProbe's declarative-inference floor for the
         * same L0-surface-stand-in reason.
         */
        const val CONFIDENCE_DECLARATIVE = 0.70

        /**
         * Degraded confidence (0.50) when the PackageManager view returns
         * an empty list — Android 11+ visibility filter is likely in
         * effect and the probe's signal source is structurally blind.
         */
        const val CONFIDENCE_DEGRADED = 0.50

        const val METHOD =
            "Declarative inference of non-standard WebView implementation: " +
                "absence of com.google.android.webview, presence of " +
                "browse-replacement WebView providers (Brave/Kiwi/Bromite/" +
                "DuckDuckGo), or WebView-disable system properties"

        /**
         * True iff any of [NON_STANDARD_WEBVIEW_PROVIDERS] is in the given
         * installed-packages list. Helper isolated for testability.
         */
        internal fun hasNonStandardWebViewProvider(installedPackages: List<String>): Boolean =
            installedPackages.any { it in NON_STANDARD_WEBVIEW_PROVIDERS }

        /**
         * The list of non-standard WebView providers that are actually
         * present in the given installed-packages list. Used for evidence-
         * row population.
         */
        internal fun listNonStandardProviders(installedPackages: List<String>): List<String> =
            installedPackages.filter { it in NON_STANDARD_WEBVIEW_PROVIDERS }
    }

    override suspend fun run(ctx: ProbeContext): ProbeResult {
        val start = System.currentTimeMillis()
        return try {
            val pm = try {
                ctx.queryPackageManager()
            } catch (_: Throwable) {
                null
            }

            // Visibility-filter heuristic: same shape as rank-10 InstalledAppsProbe.
            // If listInstalledPackages() returns empty, the caller is almost
            // certainly subject to Android 11+ package visibility filtering
            // and any isPackageInstalled() check is structurally blind.
            val installedPackages: List<String> = try {
                pm?.listInstalledPackages() ?: emptyList()
            } catch (_: Throwable) {
                emptyList()
            }
            val installedListEmpty = installedPackages.isEmpty()

            val chromiumWebViewPresent: Boolean = try {
                pm?.isPackageInstalled(PKG_CHROMIUM_WEBVIEW) == true
            } catch (_: Throwable) {
                false
            }

            // Use the installedPackages list as the source of truth for
            // non-standard providers — same data source as the visibility
            // gating, and the test fakes only need to populate one path.
            val nonStandardProviders = listNonStandardProviders(installedPackages)

            val webViewDisabledProp: String? = try {
                ctx.getSystemProperty(PROP_WEBVIEW_DISABLED)
            } catch (_: Throwable) {
                null
            }
            val webViewDisabled = webViewDisabledProp == "1"

            val safeBrowsingDisabledProp: String? = try {
                ctx.getSystemProperty(PROP_DISABLE_SAFE_BROWSING)
            } catch (_: Throwable) {
                null
            }
            val safeBrowsingDisabled = safeBrowsingDisabledProp == "1"

            // Visibility-filter guard: only treat "Chromium WebView absent"
            // as a signal when the PackageManager view actually returned a
            // populated list. Otherwise the absence is an artifact of the
            // Android 11+ visibility filter blocking the call site, not a
            // real ground-truth absence of the package on the device.
            val chromiumWebViewMissing = !chromiumWebViewPresent && !installedListEmpty

            val (pattern, score) = when {
                chromiumWebViewMissing ->
                    PATTERN_WEBVIEW_PROVIDER_MISSING to SCORE_WEBVIEW_PROVIDER_MISSING
                nonStandardProviders.isNotEmpty() ->
                    PATTERN_NON_STANDARD_WEBVIEW_INSTALLED to SCORE_NON_STANDARD_WEBVIEW_INSTALLED
                webViewDisabled ->
                    PATTERN_WEBVIEW_DISABLED_PROP to SCORE_WEBVIEW_DISABLED_PROP
                safeBrowsingDisabled ->
                    PATTERN_SAFE_BROWSING_DISABLED_PROP to SCORE_SAFE_BROWSING_DISABLED_PROP
                else ->
                    PATTERN_CLEAN to SCORE_CLEAN
            }

            val confidence = if (installedListEmpty && score == SCORE_CLEAN) {
                // Empty list + no signal == structurally blind (visibility
                // filter ate our observation). Use the more degraded floor.
                CONFIDENCE_DEGRADED
            } else {
                CONFIDENCE_DECLARATIVE
            }

            val nonStandardDisplay = if (nonStandardProviders.isEmpty()) {
                "none"
            } else {
                nonStandardProviders.joinToString(",")
            }

            val evidence = listOf(
                Evidence(
                    key = "webview.chromium_provider_present",
                    value = chromiumWebViewPresent.toString(),
                    expected = "true",
                ),
                Evidence(
                    key = "webview.non_standard_providers",
                    value = nonStandardDisplay,
                    expected = "none",
                ),
                Evidence(
                    key = "webview.disabled_prop",
                    value = webViewDisabledProp ?: "<unset>",
                    expected = "<unset>",
                ),
                Evidence(
                    key = "webview.safe_browsing_disabled_prop",
                    value = safeBrowsingDisabledProp ?: "<unset>",
                    expected = "<unset>",
                ),
                Evidence(
                    key = "webview.installed_list_empty",
                    value = installedListEmpty.toString(),
                    expected = "false",
                ),
                Evidence(
                    key = "canvas_fingerprint.pattern",
                    value = pattern,
                    expected = PATTERN_CLEAN,
                ),
            )

            ProbeResult(
                score = score,
                confidence = confidence,
                evidence = evidence,
                method = METHOD,
                runtimeMs = System.currentTimeMillis() - start,
            )
        } catch (e: Throwable) {
            ProbeResult.failed(
                "CanvasFingerprintProbe: ${e.message ?: e.javaClass.simpleName}",
                runtimeMs = System.currentTimeMillis() - start,
            )
        }
    }
}
